version: '3'
services:
  stroodle-backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./backend:/api-app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/StroodleDatabase
    command: [ "sh", "./docker-entrypoint.sh" ]
  stroodle-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
