# Base image containing Java runtime and Maven
# Base image containing Java runtime and Maven
FROM maven:3.8.3-openjdk-17-slim

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Create app directory
RUN mkdir /api-app
WORKDIR /api-app

# Install app dependencies
COPY pom.xml ./
RUN mvn dependency:go-offline

# Bundle app source
COPY . .

# Run spring boot and add system property to enable spring devtools
# Run spring boot and add system property to enable spring devtools
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dspring.devtools.restart.enabled=true"]
