# Start with a base image containing Java runtime and Maven
FROM maven:3.8.3-openjdk-17-slim

# Add Maintainer Info
LABEL maintainer="example@example.com"

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Create app directory
RUN mkdir /api-app
WORKDIR /api-app

# Install app dependencies
COPY pom.xml ./
RUN mvn dependency:go-offline

# Bundle app source
COPY . .

# Add the application's jar to the container
ARG JAR_FILE=target/backend-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} stroodle-backend.jar

# Copy the entrypoint script into the image
COPY docker-entrypoint.sh ./

# Make the entrypoint script executable
RUN chmod +x docker-entrypoint.sh

# Run the app
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]