app:
  origin: http://localhost:3000
  #origin: https://stroodle.online

azure:
  client-id: c0227c75-01a8-4859-afba-58c6e2031967
  client-secret: #ask
  authority: https://login.microsoftonline.com/9fd843f0-d6da-45c8-a7dd-a76889e41055
  redirect-uri: http://localhost:8081/api/outlook/connect

keycloak:
  auth-server-url: https://login.stroodle.online
  realm: Stroodle
  resource: stroodle-rest-api
  credentials:
    secret: E6rjyoGAO7JO4NRE55KYtTLP7yT9UsBG

spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://mongo:27017/StroodleDatabase
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.stroodle.online/realms/Stroodle
          jwk-set-uri: https://login.stroodle.online/realms/Stroodle/protocol/openid-connect/certs

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: stroodle-rest-api
      principle-attribute: preferred_username
