name: Deploy to Debian Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Stop and clean up Docker
      run: |
        ssh -o StrictHostKeyChecking=no debian@193.197.230.60 << 'EOF'
          docker stop $(docker ps -aq)
          docker container prune -f
          docker image prune -f
          docker volume ls -q | grep -v "stroodle_mongo-data" | xargs -r docker volume rm
          docker network prune -f
        EOF

    - name: Clean up old files on remote server
      run: ssh -o StrictHostKeyChecking=no debian@193.197.230.60 'sudo rm -rf /home/debian/stroodle/*'

    - name: Copy files via SCP
      run: scp -r -o StrictHostKeyChecking=no $(ls | grep -v '^deployment.yml$') debian@193.197.230.60:/home/debian/stroodle

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no debian@193.197.230.60 << 'EOF'
          cd /home/debian/stroodle
          docker-compose up -d --build
        EOF
