name: Deploy to Debian Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create deployment directory on remote server
      run: |
        ssh -o StrictHostKeyChecking=no debian@193.197.230.60 'mkdir -p /home/debian/stroodle'

    - name: Archive files
      run: tar -czf deployment.tar.gz .

    - name: Copy files via SCP
      run: scp -o StrictHostKeyChecking=no deployment.tar.gz debian@193.197.230.60:/home/debian/stroodle/deployment.tar.gz

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no debian@193.197.230.60 'cd /home/debian/stroodle && tar -xzf deployment.tar.gz && docker-compose down && docker-compose up -d'
