name: Deploy to Debian Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: /home/debian/stroodle
      run: |
        ssh -o StrictHostKeyChecking=no debian@$SERVER_IP << EOF
          set -e
          export DEPLOY_PATH=${DEPLOY_PATH}
          
          # Create deployment directory if not exists
          mkdir -p \$DEPLOY_PATH

          # Clean up old files
          sudo rm -rf \$DEPLOY_PATH/*

          # Copy files
          scp -r -o StrictHostKeyChecking=no \$(ls | grep -v '^deployment.yml$') debian@\$SERVER_IP:\$DEPLOY_PATH

          # Clean up Docker volumes except mongo-data
          docker volume rm \$(docker volume ls -qf dangling=true | grep -v "stroodle_mongo-data")

          # Clean up unused Docker resources
          docker container prune -f
          docker image prune -f
          docker network prune -f

          # Deploy application
          cd \$DEPLOY_PATH
          docker-compose down
          docker-compose up -d --build
        EOF
