name: Deploy to Debian Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      REMOTE_PATH: /home/debian/stroodle

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Stop and clean up Docker
      run: |
        ssh -o StrictHostKeyChecking=no debian@${{ env.SERVER_IP }} << 'EOF'
          docker stop $(docker ps -aq)
          docker container prune -f
          docker image prune -f
          docker volume ls -q | grep -v "stroodle_mongo-data" | xargs -r docker volume rm
          docker network prune -f
        EOF

    - name: Clean up old files on remote server
      run: |
        ssh -o StrictHostKeyChecking=no \
        debian@${{ env.SERVER_IP }} 'sudo rm -rf ${{ env.REMOTE_PATH }}/*'

    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no \
        $(ls | grep -v '^deploy.yml$') \
        debian@${{ env.SERVER_IP }}:${{ env.REMOTE_PATH }}

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no debian@${{ env.SERVER_IP }} << 'EOF'
          cd ${{ env.REMOTE_PATH }}
          docker-compose up -d --build
        EOF


